export const VIEWPORT = Object.freeze({ width: 1280, height: 720 });
export const ACCEPTANCE_LEVELS = Object.freeze(["L0", "L1", "L2", "L3", "L4"]);

export const TUNING = Object.freeze({
  fixedStep: 1 / 120,
  maxFrameDelta: 0.1,
  playerRadius: 18,
  gravity: 1550,
  terminalSpeed: 1180,
  runSpeed: 350,
  runAcceleration: 2500,
  airAcceleration: 1100,
  groundFriction: 2900,
  jumpSpeed: 590,
  wallJumpUpSpeed: 545,
  wallJumpAwaySpeed: 380,
  wallSlideSpeed: 85,
  coyoteTime: 0.12,
  jumpBufferTime: 0.12,
  ropeRange: 470,
  ropeAnchorAssist: 92,
  ropeSurfaceAssist: 58,
  ropeMinimumTargetDistance: 72,
  ropeMinimumLength: 82,
  ropeMaximumLength: 470,
  ropeCost: 0.5,
  ropeLaunchSpeed: 2200,
  ropeRetractSpeed: 2800,
  ropeAnimationSagRatio: 0.14,
  ropePullStrength: 13,
  ropeReelAcceleration: 1050,
  ropeReelMaximumSpeed: 480,
  ropeReelDeceleration: 1000,
  ropeWinchAcceleration: 360,
  ropeWinchSpeedFactor: 1.15,
  ropeWinchCompletionBoost: 240,
  ropeVisualSmoothing: 7.5,
  ropeVisualMinimumSag: 2,
  ropeVisualMaximumSag: 72,
  ropeVisualSagRatio: 0.18,
  maximumSwingSpeed: 930,
  swingInputSmoothing: 11,
  swingAcceleration: 920,
  swingBraking: 1480,
  swingTargetSpeed: 720,
  swingStartKickSpeed: 82,
  swingPumpFullSpeed: 240,
  ropeSwingDamping: 0.14,
  hardBarSwingDamping: 0.48,
  hardBarCost: 1.25,
  hardBarMinimumLength: 120,
  hardBarMaximumLength: 330,
  hardBarThickness: 10,
  dashSpeed: 850,
  dashDuration: 0.16,
  bashRange: 185,
  bashCost: 0.75,
  bashSpeed: 960,
  bashTargetCooldown: 0.55,
  bashAimDuration: 0.9,
  glideGravityScale: 0.2,
  glideMaximumFallSpeed: 190,
  glideWindMultiplier: 1.9,
  glideUpdraftEntrySpeed: 300,
  glideUpdraftMaximumSpeed: 520,
  glideUpdraftExitDeceleration: 220,
  glideUpdraftExitDampingDuration: 1.05,
  maximumHealth: 5,
  maximumEnergy: 6,
  safeEnergyFloor: 2,
  safeEnergyDelay: 0.65,
  safeEnergyRegen: 1.35,
  damageInvulnerability: 1.0,
  damageRecoveryWindow: 0.9,
  damageLiftSpeed: 370,
  damageAwaySpeed: 150,
  goalActivationPadding: 26,
  rotationDuration: 1.25,
  cameraFollow: 7.5,
  cameraLookAhead: 0.18,
  respawnDelay: 0.45
});

export const ABILITIES = Object.freeze({
  rope: { id: "rope", name: "软绳", defaultUnlocked: true },
  hardBar: { id: "hardBar", name: "硬杆", defaultUnlocked: true },
  wallGrab: { id: "wallGrab", name: "墙抓", defaultUnlocked: true },
  doubleJump: { id: "doubleJump", name: "二段跳", defaultUnlocked: false },
  glide: { id: "glide", name: "滑翔", defaultUnlocked: false },
  bash: { id: "bash", name: "猛击", defaultUnlocked: false },
  dash: { id: "dash", name: "冲刺", defaultUnlocked: true }
});

export const KNOWN_ABILITY_IDS = new Set(Object.keys(ABILITIES));
